name: hibiscus_healthlink
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  flutter_screenutil: ^5.5.4
  intl: ^0.17.0 
  firebase_core: ^2.14.0
  cloud_firestore: ^4.9.0
  firebase_database: ^10.3.1
  firebase_auth: ^4.19.6
  json_annotation: ^4.8.0
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_blue_plus: ^1.34.4
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

